// TODO : enums
export const Errors = {
  name    : {
    DB_ERROR                               : 'DB_ERROR',
    DB_NOT_INITIALIZED                     : 'DB_NOT_INITIALIZED',
    REDIS_ERROR                            : 'REDIS_ERROR',
    REDIS_NOT_CONNECTED                    : 'REDIS_NOT_CONNECTED',
    USER_NOT_FOUND                         : 'USER_NOT_FOUND',
    COUPON_EXISTS                          : 'COUPON_EXISTS',
    WALLET_NOT_FOUND                       : 'WALLET_NOT_FOUND',
    WALLET_SERIAL_MOBILE_SAME_USER         : 'WALLET_SERIAL_MOBILE_SAME_USER',
    WALLET_HISTORY_NOT_FOUND               : 'WALLET_HISTORY_NOT_FOUND',
    TRANSACTION_REVERSAL_NOT_PERMITTED     : 'TRANSACTION_REVERSAL_NOT_PERMITTED',
    HOSPITAL_NOT_FOUND                     : 'HOSPITAL_NOT_FOUND',
    HOSPITAL_FACILITY_NOT_FOUND            : 'HOSPITAL_FACILITY_NOT_FOUND',
    COUPON_UPDATE_NOT_PERMITTED            : 'COUPON_UPDATE_NOT_PERMITTED',
    INVALID_PARAMS                         : 'INVALID_PARAMS',
    LOYALTY_BENEFIT_NOT_FOUND              : 'LOYALTY_BENEFIT_NOT_FOUND',
    CASHBACK_NOT_UNIQUE                    : 'CASHBACK_NOT_UNIQUE',
    INVALID_FIELD                          : 'INVALID_FIELD',
    TEMPLATE_ALREADY_EXISTS                : 'TEMPLATE_ALREADY_EXISTS',
    TEMPLATE_NOT_UNIQUE                    : 'TEMPLATE_NOT_UNIQUE',
    STATUS_NOT_SAME                        : 'STATUS_NOT_SAME',
    TEMPLATE_NOT_FOUND                     : 'TEMPLATE_NOT_FOUND',
    TEMPLATE_NOT_ACTIVE                    : 'TEMPLATE_NOT_ACTIVE',
    DUPLICATE_EMAIL_FOUND                  : 'DUPLICATE_EMAIL_FOUND',
    DATE_TIME_RANGE_NOT_PERMITTED          : 'DATE_TIME_RANGE_NOT_PERMITTED',
    NETWORK_NOT_FOUND                      : 'NETWORK_NOT_FOUND',
    UNKNOWN_ERROR                          : 'UNKNOWN_ERROR',
    BONUS_CASH_COUPON_INSERT_NOT_PERMITTED : 'BONUS_CASH_COUPON_INSERT_NOT_PERMITTED',
    BONUS_CASH_COUPON_UPDATE_NOT_PERMITTED : 'BONUS_CASH_COUPON_UPDATE_NOT_PERMITTED',
    NOT_FOUND                              : 'NOT_FOUND',
    INVALID_INSURANCE_VENDOR_ID            : 'INVALID_INSURANCE_VENDOR_ID',
    EMAIL_SENDING_FAILURE                  : 'EMAIL_SENDING_FAILURE',
    ERROR_IN_CONVERTING_JSON_TO_EXCEL      : 'ERROR_IN_CONVERTING_JSON_TO_EXCEL',
    RECIEVER_EMAILS_REQUIRED               : 'RECIEVER_EMAILS_REQUIRED',
    EMAIL_SUBJECT_REQUIRED                 : 'EMAIL_SUBJECT_REQUIRED', 
    EMAIL_BODY_REQUIRED                    : 'EMAIL_BODY_REQUIRED',
    USER_ALREADY_INACTIVE                  : 'USER_ALREADY_INACTIVE',
    COUPON_MAPPING_EXISTS                  : 'COUPON_MAPPING_EXISTS',
    INVALID_STATUS                         : 'INVALID_STATUS',
    INVALID_COUPON_MAPPING                 : 'INVALID_COUPON_MAPPING',
    SAME_STATUS                            : 'SAME_STATUS',
    INVALID_MAPPING_ID                     : 'INVALID_MAPPING_ID',
    HOSPITAL_COUPON_NOT_FOUND              : 'HOSPITAL_COUPON_NOT_FOUND',
    EMAILS_NOT_FOUND                       : 'EMAILS_NOT_FOUND',
    INVALID_EMAILS                         : 'INVALID_EMAILS',
    DUPLICATE_TO_FOUND                     : 'DUPLICATE_TO_FOUND',
    DUPLICATE_CC_FOUND                     : 'DUPLICATE_CC_FOUND',
    EMAIL_LIMIT_EXCEEDS                    : 'EMAIL_LIMIT_EXCEEDS',
    KIT_TYPE_NOT_UNIQUE                    : 'KIT_TYPE_NOT_UNIQUE',
    INVALID_UPDATES                        : 'INVALID_UPDATES',
    HOSPITAL_MAPPING_UPDATE_NOT_PERMITTED  : 'HOSPITAL_MAPPING_UPDATE_NOT_PERMITTED',
    INVALID_WALLET_SERIAL                  : 'INVALID_WALLET_SERIAL',
    DUPLICATE_WALLET_SERIAL                : 'DUPLICATE_WALLET_SERIAL',
    LBO_IDS_NOT_UNIQUE                     : 'LBO_IDS_NOT_UNIQUE',
    USER_ALREADY_PRESENT                   : 'USER_ALREADY_PRESENT',
    MOBILE_ALREADY_MAPPED                  : 'MOBILE_ALREADY_MAPPED',
    INVALID_MOBILE                         : 'INVALID_MOBILE',
    INVALID_EMAIL                          : 'INVALID_EMAIL',
    INVALID_KIT_TYPE                       : 'INVALID_KIT_TYPE',
    HOSPITAL_PICKUP_NOT_FOUND              : 'HOSPITAL_PICKUP_NOT_FOUND',
    HOSPITAL_PICKUP_STATUS_CLOSED          : 'HOSPITAL_PICKUP_STATUS_CLOSED',
    HOSPITAL_KIT_AMOUNT_MAPPING_NOT_FOUND  : 'HOSPITAL_KIT_AMOUNT_MAPPING_NOT_FOUND',
    DUPLICATE_KIT_INVENTORY_FOUND          : 'DUPLICATE_KIT_INVENTORY_FOUND',
    DUPLICATE_HOSPITAL_PICKUP_FOUND        : 'DUPLICATE_HOSPITAL_PICKUP_FOUND',
    INSUFFICIENT_DATA                      : 'INSUFFICIENT_DATA',
    INVALID_HOSPITAL_NAME                  : 'INVALID_HOSPITAL_NAME',
    HOSPITAL_CLAIM_RAISED                  : 'HOSPITAL_CLAIM_RAISED',
    SUB_HOSP_USER_NOT_FOUND                : 'SUB_HOSPITAL_USER_NOT_FOUND', 
    PICKUP_DEPOSIT_NOT_FOUND               : 'PICKUP_DEPOSIT_NOT_FOUND',
    PICKUP_DEPOSIT_CHANGE_NOT_PERMITTED    : 'PICKUP_DEPOSIT_CHANGE_NOT_PERMITTED',
    DIGITAL_COMMUNICATION_NOT_FOUND        : 'DIGITAL_COMMUNICATION_NOT_FOUND',
    EMAIL_METADATA_NOT_FOUND               : 'EMAIL_METADATA_NOT_FOUND',
    USER_ALREADY_ACTIVE                    : 'USER_ALREADY_ACTIVE',
    INVALID_LOCATION_NAME                  : 'INVALID_LOCATION_NAME',
    INVALID_PINCODE                        : 'INVALID_PINCODE',
    INVALID_CITY_ID                        : 'INVALID_CITY_ID',
    INVALID_CITY_NAME                      : 'INVALID_CITY_NAME',
    INVALID_STATE_ID                       : 'INVALID_STATE_ID',
    CITY_NOT_FOUND                         : 'CITY_NOT_FOUND',
    STATE_NOT_FOUND                        : 'STATE_NOT_FOUND',
    CITY_EXISTS                            : 'CITY_EXISTS',
    LOCATION_EXISTS                        : 'LOCATION_EXISTS',
    INVALID_ID                             : 'INVALID_ID',
    INVALID_AREA                           : 'INVALID_AREA',
    LOCATION_NOT_FOUND                     : 'LOCATION_NOT_FOUND',
    LOYALTY_BENEFIT_OFFERING_FOUND         : 'LOYALTY_BENEFIT_OFFERING_FOUND',
    INVALID_SPECIALIZATION                 : 'INVALID_SPECIALIZATION',
    FILE_UPLOAD_ERROR                      : 'FILE_UPLOAD_ERROR',
    HOSPITAL_MAPPING_EXISTS                : 'HOSPITAL_MAPPING_EXISTS',
    HOSPITAL_MAPPING_NOT_EXISTS            : 'HOSPITAL_MAPPING_NOT_EXISTS',
    PRODUCT_TYPE_NOT_FOUND                 : 'PRODUCT_TYPE_NOT_FOUND',
    KIT_TYPE_NOT_FOUND                     : 'KIT_TYPE_NOT_FOUND',
    LAB_TEST_REQUEST_UPDATE_NOT_PERMITTED  : 'LAB_TEST_REQUEST_UPDATE_NOT_PERMITTED',
    LAB_TEST_REQUEST_NOT_FOUND             : 'LAB_TEST_REQUEST_NOT_FOUND',
    INVALID_LAB_TEST_REQUEST_STATUS        : 'INVALID_LAB_TEST_REQUEST_STATUS',
    LAB_TEST_REQUEST_STATUS_UPDATED        : 'LAB_TEST_REQUEST_STATUS_UPDATED',
    FILE_STORAGE_ERROR                     : 'FILE_STORAGE_ERROR',
    UPDATE_UTR_API_ERROR                   : 'UPDATE_UTR_API_ERROR',
    KIT_PAYMENT_NOT_VERIFIED               : 'KIT_PAYMENT_NOT_VERIFIED',
    INVALID_TOKEN                          : 'INVALID_TOKEN',
    INVALID_FILENAME                       : 'INVALID_FILENAME',
    EMPLOYEE_NOT_FOUND                     : 'EMPLOYEE_NOT_FOUND',
    INTERNAL_SERVER_ERROR                  : 'INTERNAL_SERVER_ERROR',
    FILE_NOT_FOUND                         : 'FILE_NOT_FOUND',
    FILE_ALREADY_EXISTS                    : 'FILE_ALREADY_EXISTS',
    INVALID_LOGO_URL                       : 'INVALID_LOGO_URL',
    INVALID_USER_TYPE                      : 'INVALID_USER_TYPE',
    INVALID_DATE_OF_DEPOSIT                : 'INVALID_DATE_OF_DEPOSIT',
    INVALID_REMARKS                        : 'INVALID_REMARKS',
    INVALID_NETWORK_DATA                   : 'INVALID_NETWORK_DATA',
    WALLET_HISTORY_ID                      : 'WALLET_HISTORY_ID',
    INVALID_COUPONS                        : 'INVALID_COUPONS',
    INVALID_USER_EMAIL                     : 'INVALID_USER_EMAIL',
    INVALID_COUPON_CODE                    : 'INVALID_COUPON_CODE',
    INVALID_POS_TID                        : 'INVALID_POS_TID',
    DB_DOWN                                : 'DB_DOWN',
    ENUM_NOT_FOUND                         : 'ENUM_NOT_FOUND',
    ERROR_IN_CONVERTING_EXCEL_TO_JSON      : 'ERROR_IN_CONVERTING_EXCEL_TO_JSON',
    INVALID_HUBNAME                        : 'INVALID_HUBNAME',
    HUBNAME_NOT_FOUND                      : 'HUBNAME_NOT_FOUND',
    DUPLICATE_KIT_FOUND                    : 'DUPLICATE_KIT_FOUND',
    INVOICE_NUMBER_NOT_FOUND               : 'INVOICE_NUMBER_NOT_FOUND',
    KIT_INSERTION_ERROR                    : 'KIT_INSERTION_ERROR',
    INVALID_SHEET_DATA                     : 'INVALID_SHEET_DATA',
    MEDIA_GROUP_EXISTS                     : 'MEDIA_GROUP_EXISTS',
    MEDIA_GROUP_NOT_FOUND                  : 'MEDIA_GROUP_NOT_FOUND',
    WALLET_MAPPING_UPDATE_NOT_PERMITTED    : 'WALLET_MAPPING_UPDATE_NOT_PERMITTED',
    HOSPITAL_WALLET_COUPON_NOT_FOUND       : 'HOSPITAL_WALLET_COUPON_NOT_FOUND',
    WALLET_MAPPING_EXISTS                  : 'WALLET_MAPPING_EXISTS',
    PDF_GENERATION_ERROR                   : 'PDF_GENERATION_ERROR',
    NBFC_EXISTS                            : 'NBFC_EXISTS',
    NBFC_NOT_FOUND                         : 'NBFC_NOT_FOUND',
    NBFC_PRODUCT_NOT_FOUND                 : 'NBFC_PRODUCT_NOT_FOUND',
    NBFC_PRODUCT_EXISTS                    : 'NBFC_PRODUCT_EXISTS',
    INVALID_LAB_TEST_PAYMENT_STATUS        : 'INVALID_LAB_TEST_PAYMENT_STATUS',
    NBFC_NOT_ACTIVE                        : 'NBFC_NOT_ACTIVE',
    ERROR_SENDING_SMS                      : 'ERROR_SENDING_SMS',
    LAB_TEST_PAYMENT_NOT_PERMITTED         : 'LAB_TEST_PAYMENT_NOT_PERMITTED',
    LAB_TEST_UPDATION_IN_PROGRESS          : 'LAB_TEST_UPDATION_IN_PROGRESS'
  },
  message : {
    DB_ERROR                               : 'Error occurred in executing DB query.',
    DB_NOT_INITIALIZED                     : 'DB is not initialized.',
    REDIS_ERROR                            : 'Error occurred in executing redis command.',
    REDIS_NOT_CONNECTED                    : 'Redis client is not connected to the redis server.',
    DB_DOWN                                : 'DB is down.',
    USER_NOT_FOUND                         : 'User not found for the given id.',
    INVALID_POS_TID                        : 'Pos terminal id is invalid.',
    INVALID_COUPON_CODE                    : 'Coupon name is required.',
    INVALID_USER_EMAIL                     : 'User email is missing or required.',
    COUPON_EXISTS                          : 'This coupon name already exists.',
    INVALID_HOSPITAL_NAME                  : 'Hopital name is missing or invalid.',
    INVALID_COUPONS                        : 'Please add atleast one coupon.',
    INVALID_MOBILE                         : 'Mobile number is invalid or missing.',
    INVALID_WALLET_SERIAL                  : 'Wallet serial is invalid or missing.',
    WALLET_NOT_FOUND                       : 'Wallet not found for given customer.',
    WALLET_SERIAL_MOBILE_SAME_USER         : 'Mobile and wallet serial do not refer to the same user.',
    WALLET_HISTORY_ID                      : 'Wallet history id is required.',
    WALLET_HISTORY_NOT_FOUND               : 'Wallet transaction is not found for given wallet history id.',
    TRANSACTION_REVERSAL_NOT_PERMITTED     : 'This transaction cannot be reversed because <reason>.',
    HOSPITAL_NOT_FOUND                     : 'Hospital does not exist.',
    HOSPITAL_FACILITY_NOT_FOUND            : 'Given facility does not exist for the hospital.',
    INVALID_NETWORK_DATA                   : 'Given network array is not valid',
    INVALID_FIELD                          : 'The given <field> is invalid.',
    COUPON_UPDATE_NOT_PERMITTED            : 'Given coupon cannot be updated.',
    INVALID_PARAMS                         : 'Given API params are invalid.',
    LOYALTY_BENEFIT_NOT_FOUND              : 'Given loyalty benefit offering not found in DB.',
    CASHBACK_NOT_UNIQUE                    : 'Multiple entries for given cashback id.',
    TEMPLATE_ALREADY_EXISTS                : 'The template you are trying to add already exists.',
    TEMPLATE_NOT_UNIQUE                    : 'Multiple entries for given id.',
    STATUS_NOT_SAME                        : 'Status is not same for given ids.',
    TEMPLATE_NOT_FOUND                     : 'Template does not exists.',
    TEMPLATE_NOT_ACTIVE                    : 'Template is not active.',
    DUPLICATE_EMAIL_FOUND                  : 'Duplicate emails are not allowed.',
    DATE_TIME_RANGE_NOT_PERMITTED          : 'Given date time range is not permitted.',
    NETWORK_NOT_FOUND                      : 'Given network id is not found',
    UNKNOWN_ERROR                          : 'Some error occured. Please try again later.',
    BONUS_CASH_COUPON_INSERT_NOT_PERMITTED : 'Bonus Cash coupon can not be added.',
    BONUS_CASH_COUPON_UPDATE_NOT_PERMITTED : 'Bonus Cash coupon can not be updated.',
    INVALID_INSURANCE_VENDOR_ID            : 'The insurance vendor id is missing or invalid.',
    EMAIL_SENDING_FAILURE                  : 'Error occur while sending email.',
    ERROR_IN_CONVERTING_JSON_TO_EXCEL      : 'Error in converting json to excel.',
    RECIEVER_EMAILS_REQUIRED               : 'Reciever emails is required',
    EMAIL_SUBJECT_REQUIRED                 : 'Email subject is required for email.',
    EMAIL_BODY_REQUIRED                    : 'Email body is required for email.',
    USER_ALREADY_INACTIVE                  : 'Given user is already inactive.',
    COUPON_MAPPING_EXISTS                  : 'The coupon mapping you are trying to add already exists.',
    INVALID_STATUS                         : 'The given status is invalid or missing.',
    INVALID_COUPON_MAPPING                 : 'The given coupon mapping is invalid or missing.',
    SAME_STATUS                            : 'Some coupons are already <status>.',
    INVALID_MAPPING_ID                     : 'Given mapping id is not unique or invalid.',
    HOSPITAL_COUPON_NOT_FOUND              : 'Hospital coupon not found.',
    INVALID_REMARKS                        : 'Hospital remarks is invalid.',
    EMAILS_NOT_FOUND                       : 'Email ids are not found.',
    INVALID_EMAILS                         : 'Email ids are invalid',
    DUPLICATE_TO_FOUND                     : 'To emails should be unique',
    DUPLICATE_CC_FOUND                     : 'Cc emails should be unique',
    EMAIL_LIMIT_EXCEEDS                    : 'More than <limit> emails in <field> is invalid.',
    KIT_TYPE_NOT_UNIQUE                    : 'Kit type is not unique.',
    INVALID_UPDATES                        : 'Given updates are invalid for given type.',
    HOSPITAL_MAPPING_UPDATE_NOT_PERMITTED  : 'Given hospital mapping can not be updated.',
    DUPLICATE_WALLET_SERIAL                : 'Duplicate wallet serial found.',
    LBO_IDS_NOT_UNIQUE                     : 'Loyalty benefit offering ids are not unique.',
    USER_ALREADY_PRESENT                   : 'The user with same information already present',
    MOBILE_ALREADY_MAPPED                  : 'Given mobile number is already mapped with other user.',
    INVALID_EMAIL                          : 'Email id is missing or invalid.',
    INSUFFICIENT_DATA                      : 'Given data is insufficient.',
    INVALID_KIT_TYPE                       : 'Kit type is required or invalid.',
    HOSPITAL_PICKUP_NOT_FOUND              : 'Hospital pickup not found',
    HOSPITAL_PICKUP_STATUS_CLOSED          : 'Hospital pickup is already closed for this customer.',
    HOSPITAL_KIT_AMOUNT_MAPPING_NOT_FOUND  : 'Hospital Kit amount mapping not found',
    DUPLICATE_KIT_INVENTORY_FOUND          : 'More than one kit is assigned to same customer.',
    DUPLICATE_HOSPITAL_PICKUP_FOUND        : 'More than one hospital pickup status for same kit and hospital id found.',
    HOSPITAL_CLAIM_RAISED                  : 'Hospital claim is raised for given wallet.',
    SUB_HOSP_USER_NOT_FOUND                : 'Sub hospital user not found for given id.',
    INVALID_DATE_OF_DEPOSIT                : 'The given dateOfDeposit is missing or invalid.',
    PICKUP_DEPOSIT_NOT_FOUND               : 'Pickup deposit does not exists.',
    PICKUP_DEPOSIT_CHANGE_NOT_PERMITTED    : 'Pickup deposit change is not permitted.',
    DIGITAL_COMMUNICATION_NOT_FOUND        : 'Digital Communication details not found.',
    EMAIL_METADATA_NOT_FOUND               : 'Email Metadata details not found.',
    USER_ALREADY_ACTIVE                    : 'The user with same information is already active.',
    INVALID_LOCATION_NAME                  : 'Given location name is missing or invalid.',
    INVALID_PINCODE                        : 'Given pincode is missing or invalid.',
    INVALID_CITY_ID                        : 'Given city id is missing or invalid.',
    INVALID_CITY_NAME                      : 'Given city name is missing or invalid.',
    INVALID_STATE_ID                       : 'Given state id is missing or invalid.',
    CITY_NOT_FOUND                         : 'City does not exist.',
    STATE_NOT_FOUND                        : 'State does not exists for given id.',
    CITY_EXISTS                            : 'City with given details already exists.',
    LOCATION_EXISTS                        : 'Location with given details already exists.',
    INVALID_ID                             : 'Given id is missing or invalid.',
    INVALID_AREA                           : 'Given area field is missing or invalid.',
    LOCATION_NOT_FOUND                     : 'Location does not exists for given id.',
    LOYALTY_BENEFIT_OFFERING_FOUND         : 'Loyalty Benefit offering found with same type.',
    INVALID_USER_TYPE                      : 'Only user type EMPLOYEE can be activated/deactivated.',
    HOSPITAL_MAPPING_EXISTS                : 'Hospital mapping already exists',
    HOSPITAL_MAPPING_NOT_EXISTS            : 'Hospital mapping does not exists',
    INVALID_SPECIALIZATION                 : 'Given specialization is missing or invalid.',
    INVALID_LOGO_URL                       : 'Given logo url is missing or invalid.',
    FILE_UPLOAD_ERROR                      : 'Error in uploading file.',
    FILE_ALREADY_EXISTS                    : 'File with given fileName already exists. Try picking a new fileName.',
    FILE_NOT_FOUND                         : 'File does not exists.',
    LAB_TEST_REQUEST_UPDATE_NOT_PERMITTED  : 'Lab test request status update not permitted for this user.',
    LAB_TEST_REQUEST_NOT_FOUND             : 'Lab test request not found.',
    INVALID_LAB_TEST_REQUEST_STATUS        : 'Invalid lab test request status.',
    LAB_TEST_REQUEST_STATUS_UPDATED        : `Lab test request status already updated(accepted,rejected or completed).`,
    PRODUCT_TYPE_NOT_FOUND                 : 'Product type of given hospital not found.',
    KIT_PAYMENT_NOT_VERIFIED               : 'There is some mismatch between kit price, payment or the pickup raised.',
    INVALID_FILENAME                       : 'File name is invalid or missing.',
    FILE_STORAGE_ERROR                     : 'Error occurred in file storage service.',
    INVALID_TOKEN                          : 'Token is invalid or missing.',
    UPDATE_UTR_API_ERROR                   : 'Error occurred in update utr api.',
    KIT_TYPE_NOT_FOUND                     : 'Kit Type not found in DB.',
    EMPLOYEE_NOT_FOUND                     : 'Employee not found in DB.',
    INTERNAL_SERVER_ERROR                  : 'Some error occurred while calling internal server API.',
    INVALID_HUBNAME                        : 'Hub name is missing or invalid.',
    ENUM_NOT_FOUND                         : 'Enum not found in DB.',
    ERROR_IN_CONVERTING_EXCEL_TO_JSON      : 'Error occurred in converting excel to json.',
    HUBNAME_NOT_FOUND                      : 'Hub Name not found in DB.',
    DUPLICATE_KIT_FOUND                    : 'Given Kit is already present in DB.',
    INVOICE_NUMBER_NOT_FOUND               : 'Invoice number not found in DB.',
    KIT_INSERTION_ERROR                    : 'Error occurred while inserting kits in DB.',
    INVALID_SHEET_DATA                     : 'Given sheet data contains duplicate or invalid entries.',
    INVALID_SEARCH_STRING                  : 'Given search string is missing or invalid.',
    MEDIA_GROUP_EXISTS                     : 'Media Group with given details already exists.',
    INVALID_MEDIA_GROUP_ID                 : 'Media group id is invalid or missing.',
    MEDIA_GROUP_NOT_FOUND                  : 'Media Group with given details not exists.',       
    WALLET_MAPPING_UPDATE_NOT_PERMITTED    : 'Wallet coupon mapping is not permitted',
    HOSPITAL_WALLET_COUPON_NOT_FOUND       : 'Hospital Wallet Coupon not found',
    WALLET_MAPPING_EXISTS                  : 'Wallet Mapping with this coupon already exists',
    PDF_GENERATION_ERROR                   : 'Error in generating PDF document.',
    NBFC_EXISTS                            : 'Given NBFC is already present in DB.',
    NBFC_NOT_FOUND                         : 'Given NBFC is not found in DB.',
    NBFC_PRODUCT_NOT_FOUND                 : 'Given NBFC product mapping not found in DB.',
    NBFC_PRODUCT_EXISTS                    : 'Given NBFC product mapping is already present in DB.',
    NBFC_NOT_ACTIVE                        : 'Given nbfc is not active. first activate nbfc.',
    INVALID_LAB_TEST_PAYMENT_STATUS        : 'Invalid lab test request payment status.',
    LAB_TEST_UPDATION_IN_PROGRESS          : 'There is an operation in process for this lab test request.',
    ERROR_SENDING_SMS                      : 'Error in sending SMS.',
    LAB_TEST_PAYMENT_NOT_PERMITTED         : 'Lab test payment cannot be updated at the current stage.'
  }
}
